pipeline:
  name: vending machine
  identifier: vending_machine
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: bootstrap
        identifier: bootstrap
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: assume
                  identifier: assume
                  template:
                    templateRef: account.aws_assume_role
                    versionLabel: "1"
                    templateInputs:
                      type: ShellScript
                      spec:
                        environmentVariables:
                          - name: TARGET_ROLE_ARN
                            type: String
                            value: <+input>
              - step:
                  type: TerraformPlan
                  name: plan
                  identifier: plan
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: account.rssnyder
                            repoName: harness-templates
                            branch: main
                            folderPath: HaC
                      secretManagerRef: harnessSecretManager
                      backendConfig:
                        type: Inline
                        spec:
                          content: |-
                            bucket = "riley-snyder-harness-io"
                            key = "HaC/<+account.identifier>/<+pipeline.variables.org_name.toLowerCase()>"
                      environmentVariables:
                        - name: TF_VAR_org
                          value: <+pipeline.variables.org_name>
                          type: String
                        - name: TF_VAR_requestor
                          value: <+pipeline.triggeredBy.email>
                          type: String
                        - name: AWS_REGION
                          value: us-west-2
                          type: String
                        - name: AWS_ACCESS_KEY_ID
                          value: <+execution.steps.assume.output.outputVariables.AWS_ACCESS_KEY_ID>
                          type: String
                        - name: AWS_SECRET_ACCESS_KEY
                          value: <+execution.steps.assume.output.outputVariables.AWS_SECRET_ACCESS_KEY>
                          type: String
                        - name: HARNESS_PLATFORM_API_KEY
                          value: <+secrets.getValue("account.harness_api_token")>
                          type: String
                        - name: HARNESS_ACCOUNT_ID
                          value: <+account.identifier>
                          type: String
                        - name: AWS_SESSION_TOKEN
                          value: <+execution.steps.assume.output.outputVariables.AWS_SESSION_TOKEN>
                          type: String
                    provisionerIdentifier: vendingmachine
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: appove
                  identifier: appove
                  spec:
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                    approvalMessage: An organization <+pipeline.variables.org_name> was requested by <+pipeline.triggeredBy.name>/<+pipeline.triggeredBy.email>
                  timeout: 1d
              - step:
                  type: TerraformApply
                  name: apply
                  identifier: apply
                  spec:
                    provisionerIdentifier: vendingmachine
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            type: Github
                            spec:
                              gitFetchType: Branch
                              connectorRef: account.rssnyder
                              repoName: harness-templates
                              branch: main
                              folderPath: HaC
                        backendConfig:
                          type: Inline
                          spec:
                            content: |-
                              bucket = "riley-snyder-harness-io"
                              key = "HaC/<+account.identifier>/<+pipeline.variables.org_name.toLowerCase()>"
                        environmentVariables:
                          - name: TF_VAR_org
                            value: <+pipeline.variables.org_name>
                            type: String
                          - name: TF_VAR_requestor
                            value: <+pipeline.triggeredBy.email>
                            type: String
                          - name: AWS_REGION
                            value: us-west-2
                            type: String
                          - name: AWS_ACCESS_KEY_ID
                            value: <+execution.steps.assume.output.outputVariables.AWS_ACCESS_KEY_ID>
                            type: String
                          - name: AWS_SECRET_ACCESS_KEY
                            value: <+execution.steps.assume.output.outputVariables.AWS_SECRET_ACCESS_KEY>
                            type: String
                          - name: HARNESS_PLATFORM_API_KEY
                            value: <+secrets.getValue("account.harness_api_token")>
                            type: String
                          - name: HARNESS_ACCOUNT_ID
                            value: <+account.identifier>
                            type: String
                          - name: AWS_SESSION_TOKEN
                            value: <+execution.steps.assume.output.outputVariables.AWS_SESSION_TOKEN>
                            type: String
                  timeout: 10m
        tags: {}
  variables:
    - name: org_name
      type: String
      description: ""
      value: <+input>
  delegateSelectors:
    - sa-cluster
