pipeline:
  name: test
  identifier: test
  projectIdentifier: home_lab
  orgIdentifier: default
  tags: {}
  variables:
    - name: inputsets
      type: String
      description: ""
      required: false
      value: <+input>
  stages:
    - stage:
        name: trigger
        identifier: trigger
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          # Set comma as the delimiter
                          IFS=','

                          # Read the split inputsets into an array
                          # based on comma delimiter
                          read -ra newarr <<< "<+pipeline.variables.inputsets>"


                          # Print each value of the array by using
                          # the loop
                          for val in "${newarr[@]}";
                          do
                            echo "$val"
                            curl -i -X POST \
                              'https://app.harness.io/pipeline/api/pipeline/execute/deploy/inputSetList?accountIdentifier=<+account.identifier>&orgIdentifier=<+org.identifier>&projectIdentifier=<+project.identifier>' \
                              -H 'Content-Type: application/json' \
                              -H 'x-api-key: <+secrets.getValue("account.harness_api_token")>' \
                              -d '{
                                "inputSetReferences": [
                                  "$val"
                                ]
                              }'
                          done
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: sfdsfd
        identifier: sfdsfd
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1sfs
                  identifier: BuildAndPushDockerRegistry_1sfs
                  spec:
                    connectorRef: account.gitlab
                    repo: sdafsdf
                    tags:
                      - sdf
                    buildArgs:
                      something: <+input>.default("else")
