pipeline:
  name: test
  identifier: test
  projectIdentifier: home_lab
  orgIdentifier: default
  tags: {}
  variables:
    - name: inputsets
      type: String
      description: ""
      required: false
      value: <+input>
  stages:
    - stage:
        name: sfdsfd
        identifier: sfdsfd
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "hello" > test.txt
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: minio
                    region: us-east-1
                    bucket: harness
                    sourcePath: test.txt
                    endpoint: http://s3.rileysnyder.dev
