pipeline:
  name: delegate
  identifier: delegate
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.rssnyder
        repoName: harness-templates
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: get latest tag
                  identifier: get_latest_tag
                  spec:
                    connectorRef: account.dockerhub
                    image: alpine
                    shell: Sh
                    command: |-
                      apk add curl jq
                      export LATEST=$(curl -s https://hub.docker.com/v2/repositories/<+pipeline.variables.base_image>/tags\?page_size\=2 | jq -r '.results[].name' | grep -v minimal)
                    outputVariables:
                      - name: LATEST
              - step:
                  type: BuildAndPushDockerRegistry
                  name: test
                  identifier: test
                  spec:
                    connectorRef: account.dockerhub
                    repo: rssnyder/delegate
                    tags:
                      - <+pipeline.variables.test_tag>
                    dockerfile: delegate/Dockerfile
                    buildArgs:
                      DELEGATE_TAG: <+steps.get_latest_tag.output.outputVariables.LATEST>
                    resources:
                      limits:
                        memory: 2G
                        cpu: "2"
                  failureStrategies: []
              - step:
                  type: Security
                  name: scan
                  identifier: scan
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: containerImage
                      product_name: aqua-trivy
                      product_config_name: aqua-trivy
                      container_domain: docker.io
                      container_project: <+pipeline.stages.test.spec.execution.steps.test.spec.repo>
                      container_tag: <+pipeline.variables.test_tag>
                      container_type: local_image
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          serviceDependencies:
            - identifier: dind
              name: dind
              type: Service
              spec:
                connectorRef: account.dockerhub
                image: docker:dind
                privileged: true
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: delegate
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: sa
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: Rollout
                  identifier: Rollout
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: command on delegate
                  identifier: command_on_delegate
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          [ "$ACCOUNT_ID" = "<+account.identifier>>" ]
                          aws
                          gcloud
                          kubectl
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - test
                  timeout: 10m
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: publish
                  identifier: publish
                  spec:
                    connectorRef: account.dockerhub
                    image: docker
                    shell: Sh
                    command: |-
                      docker login -u rssnyder -p '<+secrets.getValue("account.dockerhub")>'
                      docker pull rssnyder/delegate:<+pipeline.variables.test_tag>
                      docker tag rssnyder/delegate:<+pipeline.variables.test_tag> rssnyder/delegate:latest
                      docker tag rssnyder/delegate:<+pipeline.variables.test_tag> rssnyder/delegate:<+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
                      docker push rssnyder/delegate:latest
                      docker push rssnyder/delegate:<+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
          sharedPaths:
            - /var/run
          serviceDependencies:
            - identifier: docker
              name: docker
              type: Service
              spec:
                connectorRef: account.dockerhub
                image: docker:dind
                privileged: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  variables:
    - name: base_image
      type: String
      description: ""
      value: harness/delegate
    - name: test_tag
      type: String
      description: ""
      value: dev
  delegateSelectors:
    - sa-cluster
