pipeline:
  name: delegate
  identifier: delegate
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.rssnyder
        repoName: harness-templates
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: get latest tag
                  identifier: get_latest_tag
                  spec:
                    connectorRef: account.dockerhub
                    image: alpine
                    shell: Sh
                    command: |-
                      apk add curl jq
                      export LATEST=$(curl -s https://hub.docker.com/v2/repositories/<+pipeline.variables.base_image>/tags\?page_size\=2 | jq -r '.results[].name' | grep -v ubi | grep -v minimal | grep -v latest | head -n 1)
                    outputVariables:
                      - name: LATEST
              - step:
                  type: BuildAndPushDockerRegistry
                  name: test
                  identifier: test
                  spec:
                    connectorRef: account.dockerhub
                    repo: rssnyder/delegate
                    tags:
                      - <+pipeline.variables.test_tag>
                    dockerfile: delegate/Dockerfile
                    buildArgs:
                      DELEGATE_TAG: <+steps.get_latest_tag.output.outputVariables.LATEST>
                    resources:
                      limits:
                        memory: 2G
                        cpu: "2"
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          serviceDependencies:
            - identifier: dind
              name: dind
              type: Service
              spec:
                connectorRef: account.dockerhub
                image: docker:dind
                privileged: true
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: delegate
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: sa
          execution:
            steps:
              - step:
                  name: create
                  identifier: create
                  template:
                    templateRef: account.create_namespace
                    versionLabel: "1"
              - step:
                  type: K8sRollingDeploy
                  name: Rollout
                  identifier: Rollout
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: command on delegate
                  identifier: command_on_delegate
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          [[ "$ACCOUNT_ID" == <+account.identifier>​​ ]]
                          echo $PATH
                          whoami
                          aws --help && gcloud --help && kubectl --help && terraform --help && terragrunt --help && serverless --help
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - test
                  timeout: 10m
                  failureStrategies: []
              - step:
                  name: remove
                  identifier: remove
                  template:
                    templateRef: account.delete_namespace
                    versionLabel: "1"
            rollbackSteps:
              - step:
                  name: delete
                  identifier: delete
                  template:
                    templateRef: account.delete_namespace
                    versionLabel: "1"
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: publish
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: publish
                  identifier: publish
                  spec:
                    connectorRef: account.dockerhub
                    image: docker
                    shell: Sh
                    command: |-
                      docker login -u rssnyder -p '<+secrets.getValue("account.dockerhub")>'
                      docker pull rssnyder/delegate:<+pipeline.variables.test_tag>
                      docker tag rssnyder/delegate:<+pipeline.variables.test_tag> rssnyder/delegate:latest
                      docker tag rssnyder/delegate:<+pipeline.variables.test_tag> rssnyder/delegate:<+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
                      docker push rssnyder/delegate:latest
                      docker push rssnyder/delegate:<+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
          sharedPaths:
            - /var/run
          serviceDependencies:
            - identifier: docker
              name: docker
              type: Service
              spec:
                connectorRef: account.dockerhub
                image: docker:dind
                privileged: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: Success
          condition: <+codebase.branch> == "main"
  variables:
    - name: base_image
      type: String
      description: ""
      value: harness/delegate
    - name: test_tag
      type: String
      description: ""
      value: dev
  delegateSelectors:
    - sa-cluster
