pipeline:
  name: delegate
  identifier: delegate
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.rssnyder
        repoName: harness-templates
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: get latest tag
                  identifier: get_latest_tag
                  spec:
                    connectorRef: account.dockerhub
                    image: alpine
                    shell: Sh
                    command: |-
                      apk add curl jq
                      export LATEST=$(curl -s https://hub.docker.com/v2/repositories/harness/delegate-immutable/tags\?page_size\=2 | jq -r '.results[].name' | grep -v minimal)
                    outputVariables:
                      - name: LATEST
              - step:
                  type: BuildAndPushDockerRegistry
                  name: test
                  identifier: test
                  spec:
                    connectorRef: account.dockerhub
                    repo: rileysnyderharnessio/delegate-immutable
                    tags:
                      - dev
                    dockerfile: delegate/Dockerfile
                    buildArgs:
                      DELEGATE_TAG: <+steps.get_latest_tag.output.outputVariables.LATEST>
                    resources:
                      limits:
                        memory: 2G
                        cpu: "2"
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: delegate
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: sa
          execution:
            steps:
              - step:
                  name: create namespace
                  identifier: create_namespace
                  template:
                    templateRef: account.create_namespace
                    versionLabel: "1"
              - step:
                  type: K8sRollingDeploy
                  name: Rollout
                  identifier: Rollout
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: command on delegate
                  identifier: command_on_delegate
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo $ACCOUNT_ID
                          aws
                          gcloud
                          kubectl
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - test
                  timeout: 10m
                  failureStrategies: []
              - step:
                  name: delete namespace
                  identifier: delete_namespace
                  template:
                    templateRef: account.delete_namespace
                    versionLabel: "1"
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  name: rollback namespace
                  identifier: rollback_namespace
                  template:
                    templateRef: account.delete_namespace
                    versionLabel: "1"
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: verify
        identifier: verify
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: verify
                  identifier: verify
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
        tags: {}
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: test
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BnP
                  identifier: BnP
                  spec:
                    connectorRef: account.dockerhub
                    repo: rileysnyderharnessio/delegate-immutable
                    tags:
                      - latest
                      - <+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
                    dockerfile: delegate/Dockerfile
                    buildArgs:
                      DELEGATE_TAG: <+pipeline.stages.test.spec.execution.steps.get_latest_tag.output.outputVariables.LATEST>
                    resources:
                      limits:
                        memory: 2G
                        cpu: "1"
          sharedPaths:
            - /var/run
  variables: []
  delegateSelectors:
    - sa-cluster
