template:
  name: run ansible playbook
  identifier: run_ansible_playbook
  versionLabel: 0.0.1
  type: Stage
  tags: {}
  spec:
    type: Custom
    spec:
      execution:
        steps:
          - stepGroup:
              name: execute
              identifier: execute
              steps:
                - step:
                    type: GitClone
                    name: clone
                    identifier: clone
                    spec:
                      connectorRef: <+input>
                      repoName: <+input>
                      build:
                        type: branch
                        spec:
                          branch: <+input>
                - step:
                    type: Run
                    name: execute
                    identifier: execute
                    spec:
                      connectorRef: account.dockerhub
                      image: pad92/ansible-alpine:9.1.0
                      shell: Sh
                      command: |-
                        cd <+execution.steps.execute.steps.clone.spec.repoName>

                        echo <+secrets.getValue("id_rsa")> | base64 -d > id_rsa
                        chmod 600 id_rsa

                        echo '<+secrets.getValue("vault_password")>' > .vault_password

                        cat > hosts << 'EOF'
                        <+execution.steps.execute.variables.host> ansible_user=<+execution.steps.execute.variables.user>
                        EOF

                        if [ -e requirements.yml ]
                        then
                            ansible-galaxy install -r requirements.yml
                        else
                            echo "no requirements.yml found"
                        fi

                        ansible-playbook --vault-password=.vault_password -i secrets.yml --private-key=id_rsa -i <+<+execution.steps.execute.variables.host> == "" ? <+execution.steps.execute.variables.host_file> : "hosts"> --extra-vars "appID=<+execution.steps.execute.variables.appID> region=<+execution.steps.execute.variables.region> <+execution.steps.execute.variables.extra_vars>" playbooks/<+execution.steps.execute.variables.playbook>
              variables:
                - name: host
                  type: String
                  value: <+input>
                  description: ""
                  required: false
                - name: host_file
                  type: String
                  value: <+input>
                  description: ""
                  required: false
                - name: user
                  type: String
                  value: <+input>
                  description: ""
                  required: false
                - name: playbook
                  type: String
                  value: <+input>
                  description: ""
                  required: false
                - name: appID
                  type: String
                  value: <+input>.allowedValues(app1,app2,app3)
                  description: ""
                  required: false
                - name: region
                  type: String
                  value: <+input>.allowedValues(centralus,westus)
                  description: ""
                  required: false
                - name: extra_vars
                  type: String
                  value: <+input>
                  description: ""
                  required: false
              stepGroupInfra:
                type: KubernetesDirect
                spec:
                  connectorRef: account._lab
                  namespace: iacm
        rollbackSteps: []
      serviceDependencies: []
  description: |-
    run ansible playbooks using container steps in k8s

    requires project level secrets:
    id_rsa: base64 encoded ssh private key
    vault_password: vault password file
  icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgdmVyc2lvbj0iMS4xIgogICBpZD0ibGF5ZXIiCiAgIHg9IjBweCIKICAgeT0iMHB4IgogICB2aWV3Qm94PSIwIDAgNDAwIDQwMCIKICAgeG1sOnNwYWNlPSJwcmVzZXJ2ZSIKICAgc29kaXBvZGk6ZG9jbmFtZT0iaWNvbi5zdmciCiAgIHdpZHRoPSI0MDAiCiAgIGhlaWdodD0iNDAwIgogICBpbmtzY2FwZTp2ZXJzaW9uPSIxLjAuMSAoMS4wLjErcjczKSIKICAgaW5rc2NhcGU6ZXhwb3J0LWZpbGVuYW1lPSIvaG9tZS9qb2huL0Rvd25sb2Fkcy9hbnNpYmxlLWljb24ucG5nIgogICBpbmtzY2FwZTpleHBvcnQteGRwaT0iNDgiCiAgIGlua3NjYXBlOmV4cG9ydC15ZHBpPSI0OCI+PG1ldGFkYXRhCiAgIGlkPSJtZXRhZGF0YTQ1Ij48cmRmOlJERj48Y2M6V29yawogICAgICAgcmRmOmFib3V0PSIiPjxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0PjxkYzp0eXBlCiAgICAgICAgIHJkZjpyZXNvdXJjZT0iaHR0cDovL3B1cmwub3JnL2RjL2RjbWl0eXBlL1N0aWxsSW1hZ2UiIC8+PGRjOnRpdGxlPjwvZGM6dGl0bGU+PC9jYzpXb3JrPjwvcmRmOlJERj48L21ldGFkYXRhPjxkZWZzCiAgIGlkPSJkZWZzNDMiPgoJCgkKCQoJCgkKCQoJCgkKCQoJCgkKCQoJCgkKCQoJCgkKPC9kZWZzPjxzb2RpcG9kaTpuYW1lZHZpZXcKICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICBib3JkZXJjb2xvcj0iIzY2NjY2NiIKICAgYm9yZGVyb3BhY2l0eT0iMSIKICAgb2JqZWN0dG9sZXJhbmNlPSIxMCIKICAgZ3JpZHRvbGVyYW5jZT0iMTAiCiAgIGd1aWRldG9sZXJhbmNlPSIxMCIKICAgaW5rc2NhcGU6cGFnZW9wYWNpdHk9IjAiCiAgIGlua3NjYXBlOnBhZ2VzaGFkb3c9IjIiCiAgIGlua3NjYXBlOndpbmRvdy13aWR0aD0iMTkyMCIKICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iOTc3IgogICBpZD0ibmFtZWR2aWV3NDEiCiAgIHNob3dncmlkPSJmYWxzZSIKICAgaW5rc2NhcGU6cGFnZWNoZWNrZXJib2FyZD0idHJ1ZSIKICAgaW5rc2NhcGU6em9vbT0iMS4wMjM3ODY1IgogICBpbmtzY2FwZTpjeD0iMTgxLjQ2OTk2IgogICBpbmtzY2FwZTpjeT0iMjQ3Ljg1ODcxIgogICBpbmtzY2FwZTp3aW5kb3cteD0iMCIKICAgaW5rc2NhcGU6d2luZG93LXk9IjM0IgogICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIxIgogICBpbmtzY2FwZTpjdXJyZW50LWxheWVyPSJsYXllciIKICAgaW5rc2NhcGU6ZG9jdW1lbnQtcm90YXRpb249IjAiIC8+CjxzdHlsZQogICB0eXBlPSJ0ZXh0L2NzcyIKICAgaWQ9InN0eWxlMiI+Cgkuc3Qwe2ZpbGw6I0NDMDAwMDt9Cgkuc3Qxe2ZpbGw6I0ZGRkZGRjt9Cjwvc3R5bGU+CjxnCiAgIGlkPSJnNTUiCiAgIHRyYW5zZm9ybT0ibWF0cml4KDIuMTExOTQzNSwwLDAsMi4xMTE5NDM1LC02Ljk0MzE4MzksLTY5Ni40NzAzOSkiPjxjaXJjbGUKICAgICBjbGFzcz0ic3QwIgogICAgIGN4PSI5Ny45ODcwODMiCiAgICAgY3k9IjQyNC40NzY1IgogICAgIHI9IjcxLjAyNDYyOCIKICAgICBpZD0iY2lyY2xlMzQiCiAgICAgc3R5bGU9ImZpbGw6I2NjMDAwMDtzdHJva2Utd2lkdGg6MC43NDk5OTYiIC8+PHBhdGgKICAgICBjbGFzcz0ic3QxIgogICAgIGQ9Im0gMTMxLjg4NjkxLDQ1Mi42MDEzMyAtMjguMzQ5ODUsLTY4LjA5OTY0IGMgLTAuNjc1LC0xLjc5OTk5IC0yLjM5OTk5LC0zLjA3NDk5IC00LjM0OTk4MiwtMi45OTk5OSAtMi4wMjQ5ODksLTAuMDc1IC0zLjgyNDk4LDEuMiAtNC40OTk5NzYsMi45OTk5OSBMIDYzLjcxMjI2NCw0NTkuMTI2MyBoIDEwLjY0OTk0NCBsIDEyLjIyNDkzNiwtMzAuNzQ5ODQgMzYuNjc0ODA2LDI5LjYyNDg0IGMgMS4wNSwxLjA1IDIuNDc0OTksMS42NSAzLjg5OTk4LDEuNzI1IDIuNzc0OTksMC4wNzUgNS4wOTk5OCwtMi4wOTk5OSA1LjE3NDk4LC00Ljk0OTk4IHYgLTAuMTUgYyAtMC4wNzUsLTAuNjc0OTkgLTAuMjI1LC0xLjM0OTk5IC0wLjQ1LC0yLjAyNDk5IHogTSA5OS4yNjIwNzgsMzk2LjgwMTYyIDExNy42MzY5OCw0NDIuMTc2MzkgODkuODg3MTI3LDQyMC4yNzY1IFoiCiAgICAgaWQ9InBhdGgzNiIKICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgIHN0eWxlPSJmaWxsOiNmZmZmZmY7c3Ryb2tlLXdpZHRoOjAuNzQ5OTk2IiAvPjwvZz4KPC9zdmc+Cg==
